version: '3'

services:
  backend:
    image: jose2506/backend:0.1
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      API_KEY: ${API_KEY}

  frontend:
    image: jose2506/frontend:lastest
    container_name: frontend
    ports:
      - "4200:4200"


